@HOST=https://localhost:8081

###

POST {{HOST}}/identity/register
Content-Type: application/json

{
  "name": "Tyroil Smoochie Wallace",
  "email": "tyroil@bar.ca",
  "password": "foobarfoobar"
}

###

POST {{HOST}}/identity/resend-verification-email
Content-Type: application/json

{
  "email": "asdf@bar.ca"
}

###

POST {{HOST}}/identity/forgot-password
Content-Type: application/json

{
  "email": ""
}

###

POST {{HOST}}/identity/login
Content-Type: application/json

{
  "email": "ericsondergard+spensesuser@fastmail.com",
  "password": "Password1!"
}

###

POST {{HOST}}/identity/logout

###

# @name homes
GET {{HOST}}/homes



###
# @name expenses
GET {{HOST}}/homes/{{homeId}}/expenses

###
# @name payments
GET {{HOST}}/homes/{{homeId}}/payments
