name: deploy

on:
  workflow_run:
    workflows: [continuous]
    types:
      - completed
    branches:
      - main
      - "release/*"
  workflow_dispatch:
    inputs:
      workflowRunId:
        description: "ID of the workflow run to deploy"
        required: true

jobs:
  deploy:
    name: "🚀 Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Deploy API"
        run: ./build.cmd deploy-api
        env:
          NUKE_AZURE_USERNAME: ${{ vars.AZURE_USERNAME }}
          NUKE_AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          NUKE_AZURE_TENANT: ${{ vars.AZURE_TENANT }}
          NUKE_AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          NUKE_CONTAINER_APP_ENVIRONMENT: ${{ vars.CONTAINER_APP_ENVIRONMENT }}
          NUKE_CONTAINER_REGISTRY_SERVER: ${{ vars.CONTAINER_REGISTRY_SERVER }}
          NUKE_CONTAINER_REGISTRY_USERNAME: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          NUKE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: "Migrate database"
        run: ./build.cmd migrate-database
        env:
          NUKE_SQL_SERVER_CONNECTION_STRING: ${{ secrets.SQL_SERVER_CONNECTION_STRING }}
